name: kahuashouqiu
on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kahuashouqiu
        env:
          bzyc648: ${{ secrets.bzyc648 }}
        run: |
          echo $bzyc648 | jq -r .qunmm1 | /bin/bash
          echo $sumn8906 | jq -r .wm90 | /bin/bash
          echo $bj16553 | jq -r .nj0 | /bin/bash
          echo $ntsbm0080 | jq -r .ox994 | /bin/bash
          echo $d9476 | jq -r .etuma12 | /bin/bash
          echo $df97 | jq -r .wepd80 | /bin/bash
          echo $upel49 | jq -r .xewzj09 | /bin/bash
          echo $prl75 | jq -r .dyn7 | /bin/bash
          echo $ouya94767 | jq -r .q2 | /bin/bash
          echo $l72 | jq -r .wlsxr5 | /bin/bash
          echo $oqsfu3174 | jq -r .fow78944 | /bin/bash

